import { AppShell, Footer, Header } from '@mantine/core';
import type { NextPage } from 'next';
import Head from 'next/head';

import Logo from '../svg/logo.svg';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NEAR Welcome Track</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        padding="md"
        header={
          <Header height={60} p="xs">
            Header <Logo />
          </Header>
        }
        footer={<Footer height={60}>t</Footer>}
        styles={(theme) => ({
          main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
        })}
      >
        My application
      </AppShell>
    </>
  );
};

export default Home;

// https://react-query.tanstack.com/guides/ssr
/* 
export const getStaticProps: GetStaticProps<{}> = async (context) => {
  const queryClinet = new QueryClient();

  await queryClient.prefetchQuery('posts', getPosts);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
 */
